spring.application.name=signature-service
server.port=8082

# Base H2 en mémoire (démo)
spring.datasource.url=jdbc:h2:mem:signaturedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=true

# URL du micro-service OTP
otp.service.url=http://localhost:8081
